apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxinstall  #reponame
  namespace: default
spec:
  interval: 15m
  path: "./nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxinstall  #reponame