apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxinstall  #reponame
  namespace: default
spec:
  interval: 1m
  url: https://github.com/sivasrinu52/fluxinstall
  ref:
    branch: main