apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-production  # The namespace for the single environment
spec:
  replicas: 1  # Set to 1 pod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80